# -*- coding: utf-8 -*-
"""wordCount

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--LlQLDKPp-pPdVKvw5LcZq6RUg7q8pO
"""

import time

def read_file(file_path):
    """
    Read the content of a file and return it as a list of words.

    Args:
        file_path (str): The path to the file.

    Returns:
        list: A list of words read from the file.
    """
    try:
        with open(file_path, 'r') as file:
            words = file.read().split()
        return words
    except FileNotFoundError as e:
        print(f"Error: File not found - {e}")
        return None
    except Exception as e:
        print(f"Error reading file: {e}")
        return None

def count_words(word_list):
    """
    Count the frequency of words in a list.

    Args:
        word_list (list): List of words.

    Returns:
        tuple: A tuple containing a dictionary of word frequencies and the elapsed time.
    """
    if not word_list:
        return None

    start_time = time.time()

    word_count = {}
    for word in word_list:
        cleaned_word = word.strip('.,!?"\'()[]{}:;')
        cleaned_word = cleaned_word.lower()
        word_count[cleaned_word] = word_count.get(cleaned_word, 0) + 1

    elapsed_time = time.time() - start_time

    return word_count, elapsed_time

def write_results_to_file(results):
    """
    Write word frequencies to a file.

    Args:
        results (dict): Dictionary containing word frequencies.
    """
    with open('WordCountResults.txt', 'w') as file:
        for word, count in results.items():
            file.write(f"{word}: {count}\n")
    # file.write(f"Elapsed Time: {results['elapsed_time']:.6f} seconds\n")

def main(file_path):
    """
    Main function to count words, print results, and write to a file.

    Args:
        file_path (str): The path to the file.
    """
    words = read_file(file_path)

    if words is None:
        return

    results = dict(zip(["word_count", "elapsed_time"], count_words(words)))

    print(f"Elapsed Time: {results['elapsed_time']:.6f} seconds")

    for word, count in results["word_count"].items():
        print(f"{word}: {count}")

    write_results_to_file(results["word_count"])

if __name__ == "__main__":
    # Use a different variable name to avoid redefining 'file_path' from outer scope
    input_file_path = 'fileWithDataP3.txt'
    main(input_file_path)